// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ratingService.proto

package hipstershop.grpc;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Empty)
    com.google.protobuf.MessageOrBuilder {
}
